"""
Known English idioms in normalized form for matching.
Phrases are stored as they appear in our n-grams: space-separated lemmas,
no determiners (DET like 'the'/'a' are skipped by the tokenizer).
e.g. "kick the bucket" -> "kick bucket", "piece of cake" -> "piece of cake".
"""

# Normalized forms only: no "the"/"a" (DET is skipped by tokenizer). Lemmas lowercase.
IDIOM_LEXICON = frozenset({
    "kick bucket",
    "piece of cake",
    "break ice",
    "hit nail on head",
    "cost arm and leg",
    "once in blue moon",
    "break leg",
    "bite bullet",
    "hit sack",
    "spill beans",
    "pull leg",
    "sit on fence",
    "when pig fly",
    "see eye to eye",
    "on same page",
    "get cold foot",
    "get cold feet",
    "blessing in disguise",
    "call it day",
    "cut corner",
    "get out of hand",
    "get act together",
    "hit book",
    "let cat out of bag",
    "make long story short",
    "miss boat",
    "on ball",
    "pull together",
    "rain cat and dog",
    "speak of devil",
    "take with grain of salt",
    "ball is in court",
    "best of both world",
    "last straw",
    "through thick and thin",
    "time fly",
    "get bent out of shape",
    "under weather",
    "up in air",
    "wrap head around",
    "double down",
    "run gamut",
    "at end of day",
    "back to drawing board",
    "beat around bush",
    "burn midnight oil",
    "by skin of teeth",
    "cut to chase",
    "devil advocate",
    "every cloud has silver lining",
    "get ball rolling",
    "get wind of",
    "give benefit of doubt",
    "go extra mile",
    "hang in there",
    "head over heel",
    "hear pin drop",
    "in heat of moment",
    "take two to tango",
    "jump on bandwagon",
    "keep chin up",
    "kill two bird with one stone",
    "let bygone be bygone",
    "long story short",
    "make mountain out of molehill",
    "no pain no gain",
    "off top of head",
    "on cloud nine",
    "on fence",
    "par for course",
    "play devil advocate",
    "pull out all stop",
    "put all egg in one basket",
    "read between line",
    "right off bat",
    "shot in dark",
    "skeleton in closet",
    "straight from horse mouth",
    "elephant in room",
    "whole nine yards",
    "throw in towel",
    "tip of iceberg",
    "up in arm",
    "when rain pour",
    "guess is as good as mine",
})


def is_idiom(phrase: str) -> bool:
    """True if the normalized phrase is in the idiom lexicon."""
    if not phrase:
        return False
    return phrase.strip().lower() in IDIOM_LEXICON
